#!/bin/bash
echo "----------------------------------------"
echo "[i] 安装"
echo "[i] 正在检查您正在运行的系统。"
if [ -f "/etc/debian_version" ]; then
        echo "[i] 检测到基于 Debian 的 Linux。"
        echo "[i] 现在将收集一些信息..."
        sudo apt-get update > /dev/null 2>&1 || echo "[!] 无法更新信息。"
        echo "[i] 现在将安装 git..."
        sudo apt-get install -y git > /dev/null 2>&1 || echo "[!] 无法安装 git。"
        echo "[i] 现在将安装 python3 和 python3-pip..."
        sudo apt-get install -y python3 python3-pip > /dev/null 2>&1 || echo "[!] 无法安装 python3。"
        echo "[i] 现在将安装 ping..."
        sudo apt-get install -y iputils-ping > /dev/null 2>&1 || echo "[!] 无法安装 ping。"
        echo "[i] 现在将安装 nmap..."
        sudo apt-get install -y nmap > /dev/null 2>&1 || echo "[!] 无法安装 nmap。"
        echo "[i] 现在将安装 bluez..."
        sudo apt-get install -y bluez > /dev/null 2>&1 || echo "[!] 无法安装 bluez。"
        echo "[i] 现在将安装 aircrack-ng..."
        sudo apt-get install -y aircrack-ng > /dev/null 2>&1 || echo "[!] 无法安装 aircrack-ng。"
        echo "[i] 现在将安装 dsniff..."
        sudo apt-get install -y dsniff > /dev/null 2>&1 || echo "[!] 无法安装 dsniff。"
        echo "[i] 现在将安装 psmisc..."
        sudo apt-get install -y psmisc > /dev/null 2>&1 || echo "[!] 无法安装 psmisc。"
        echo "[i] 现在将下载 Raven-Storm..."
        sudo git clone https://github.com/dateName/Raven-Storm.git > /dev/null 2>&1 || echo "[!] 无法下载 Raven-Storm。"
        cd Raven-Storm > /dev/null 2>&1
        echo "[i] 现在将安装依赖..."
        sudo pip3 install -r requirements.txt  > /dev/null 2>&1 || echo "[!] 无法安装依赖。"
        echo "[i] 现在将安装 Raven-Storm..."
        sudo bash ./install_to_bin.sh || echo "[!] 无法安装 Raven-Storm。"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "[i] 检测到 darwin。"
        echo "[i] 如果尚未安装 brew，则现在将安装 brew..."
        brew --help > /dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        echo "[i] 现在将安装 git..."
        sudo brew install git > /dev/null 2>&1  || echo "[!] 无法安装 git。"
        echo "[i] 现在将安装 python3 和 python3-pip..."
        sudo brew install python3 > /dev/null 2>&1  || echo "[!] 无法安装 python3。"
        echo "[i] 现在将安装 ping..."
        sudo brew install iputils-ping > /dev/null 2>&1  || echo "[!] 无法安装 ping。"
        echo "[i] 现在将安装 nmap..."
        sudo brew install nmap > /dev/null 2>&1  || echo "[!] 无法安装 nmap。"
        echo "[i] 现在将安装 bluez..."
        sudo brew install bluez > /dev/null 2>&1  || echo "[!] 无法安装 bluez。"
        echo "[i] 现在将安装 aircrack-ng..."
        sudo brew install aircrack-ng > /dev/null 2>&1  || echo "[!] 无法安装 aircrack-ng。"
        echo "[i] 现在将安装 dsniff..."
        sudo brew install dsniff > /dev/null 2>&1  || echo "[!] 无法安装 dsniff。"
        # psmisc already preinstalled for sure.
        echo "[i] 现在将下载 Raven-Storm..."
        sudo git clone https://github.com/dateName/Raven-Storm.git > /dev/null 2>&1  || echo "[!] 无法下载 Raven-Storm。"
        cd Raven-Storm > /dev/null 2>&1
        echo "[i] 现在将安装依赖..."
        sudo pip3 install -r requirements.txt  > /dev/null 2>&1 || echo "[!] 无法安装依赖。"
        echo "[i] 现在将安装 Raven-Storm..."
        sudo bash ./install_to_bin.sh  || echo "[!] 无法安装 Raven-Storm。"
elif [ -f "/etc/arch-release" ]; then  # FIXME
        echo "[i] 检测到基于 Arch 的 Linux。"
        echo "[i] 现在将安装 git..."
        sudo pacman --noconfirm -S git > /dev/null 2>&1  || echo "[!] 无法安装 git。"
        echo "[i] 现在将安装 python3 和 python3-pip..."
        sudo pacman --noconfirm -S python3 python3-pip > /dev/null 2>&1  || echo "[!] 无法安装 python3。"
        echo "[i] 现在将安装 ping..."
        sudo pacman --noconfirm -S iputils-ping > /dev/null 2>&1  || echo "[!] 无法安装 ping。"
        echo "[i] 现在将安装 nmap..."
        sudo pacman --noconfirm -S nmap > /dev/null 2>&1  || echo "[!] 无法安装 nmap。"
        echo "[i] 现在将安装 bluez..."
        sudo pacman --noconfirm -S bluez > /dev/null 2>&1  || echo "[!] 无法安装 bluez。"
        echo "[i] 现在将安装 aircrack-ng..."
        sudo pacman --noconfirm -S aircrack-ng > /dev/null 2>&1  || echo "[!] 无法安装 aircrack-ng。"
        echo "[i] 现在将安装 dsniff..."
        sudo pacman --noconfirm -S dsniff > /dev/null 2>&1  || echo "[!] 无法安装 dsniff。"
        echo "[i] 现在将安装 psmisc..."
        sudo pacman --noconfirm -S psmisc > /dev/null 2>&1 || echo "[!] Could not install psmisc."
        echo "[i] 现在将下载 Raven-Storm..."
        sudo git clone https://github.com/Taguar258/Raven-Storm.git > /dev/null 2>&1  || echo "[!] 无法下载 Raven-Storm。"
        cd Raven-Storm > /dev/null 2>&1
        echo "[i] 现在将安装依赖..."
        sudo pip3 install -r requirements.txt  > /dev/null 2>&1 || echo "[!] 无法安装依赖。"
        echo "[i] 现在将安装 Raven-Storm..."
        sudo bash ./install_to_bin.sh || echo "[!] 无法安装 Raven-Storm。"
elif [[ "$OSTYPE" == "win32" ]]; then
        echo "[!] 请在 wsl 上运行。"
else
        echo "[!] 无法检测到您的系统。"
        echo "[i] 请手动安装一些组件"
        git clone https://github.com/dateName/Raven-Storm.git > /dev/null 2>&1 || echo "[!] 请安装 git"
        cd Raven-Storm
        python3 --help > /dev/null 2>&1 || echo "[!] 请安装 python3。"
        command -v ping > /dev/null 2>&1 || echo "[!] 请安装 ping。"
        command -v l2ping > /dev/null 2>&1 || echo "[!] 请安装 bluez。"
        command -v aircrack-ng > /dev/null 2>&1 || echo "[!] 请安装 aircrack-ng。"
        command -v arpspoof > /dev/null 2>&1 || echo "[!] 请安装 dsniff。"
        command -v killall > /dev/null 2>&1 || echo "[!] 请安装 psmisc。"
        nmap --help > /dev/null 2>&1 || echo "[!] 请安装 nmap。"
        pip3 install -r requirements.txt  > /dev/null 2>&1 || echo "[!] 无法安装依赖。"
        bash ./install_to_bin.sh || echo "[i] 无法安装。"
fi

echo "[i] 完成"
exit 0
